// src/react/components/NavigationBar.jsx
import React from 'react'
import { scrollTo } from '../../shared/utils.js'

const NavigationBar = props => {
	const { top } = props

	return (
		<header id="navigation-bar" className={!top ? 'invert' : null}>
			<div className="container">
				<nav className="row navigation-inner">
					<a className="brand" onClick={scrollTo.bind(this, '#hero-section')}>
						Szarka-Kovács Roland
					</a>
					<ul className="links">
						<li>
							<button onClick={scrollTo.bind(this, '#about-section')}>About</button>
						</li>
						<li>
							<button onClick={scrollTo.bind(this, '#experience-section')}>Experience</button>
						</li>
						<li>
							<button onClick={scrollTo.bind(this, '#skills-section')}>Skills</button>
						</li>
						<li>
							<button onClick={scrollTo.bind(this, '#education-section')}>Education</button>
						</li>
						<li>
							<button onClick={scrollTo.bind(this, '#contact-section')}>Social</button>
						</li>
					</ul>
					<ul className="social-links">
						<li>
							<a href="https://github.com/szkabaroli" target="_blank">
								<i className={top ? 'lni-github' : 'lni-github-original'}></i>
							</a>
						</li>
						<li>
							<a href="https://www.facebook.com/rolandakos.szarkakovacs" target="_blank">
								<i className={top ? 'lni-facebook' : 'lni-facebook-filled'}></i>
							</a>
						</li>
						<li>
							<a href="https://www.linkedin.com/in/szarka-kovács-roland-4b7008196" target="_blank">
								<i className={top ? 'lni-linkedin' : 'lni-linkedin-filled'}></i>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</header>
	)
}

export default NavigationBar

// src/vue/components/NavigationBar.vue
<template lang="pug">
	mixin link(text)
		li
			button&attributes(attributes)=text

	mixin social-link(linkTo, src)
		li
			a(href=linkTo target="_blank")
				i(class=src)&attributes(attributes)
	
	header#navigation-bar(:class="{'invert': !top}")
		.container
			nav.row.navigation-inner
				a.brand(@click="scrollTo('#hero-section')") Szarka-Kovács Roland
				ul.links
					+link("About")(@click="scrollTo('#about-section')")
					+link("Experience")(@click="scrollTo('#experience-section')")
					+link("Skills")(@click="scrollTo('#skills-section')")
					+link("Education")(@click="scrollTo('#education-section')")
					+link("Social")(@click="scrollTo('#contact-section')")
				ul.social-links
					+social-link("https://github.com/szkabaroli")(:class="top ? 'lni-github' : 'lni-github-original'")
					+social-link("https://www.facebook.com/rolandakos.szarkakovacs")(:class="top ? 'lni-facebook' : 'lni-facebook-filled'")
					+social-link("https://www.linkedin.com/in/szarka-kovács-roland-4b7008196")(:class="top ? 'lni-linkedin' : 'lni-linkedin-filled'")
</template>

<script>
	import Vue from 'vue'
	import { scrollTo } from '../../shared/utils.js'

	export default {
		props: {
			top: {
				type: Boolean,
				required: true,
			},
		},
		methods: {
			scrollTo,
		},
	}
</script>
