// src/vue/components/AboutSection.vue
<template lang="pug">
	section#about-section
		.container
			.row.about
				h1.headline.line {{ title }}
				p.text {{ text }}
				button.btn.download
					i(class="lni-download")
					p Download CV
</template>

<script>
	import Vue from 'vue'

	export default {
		name: 'about-section',
		props: {
			title: String,
			text: String,
		},
	}
</script>

// src/react/components/AboutSection.jsx
import React from 'react'

const AboutSection = props => {
	const { title, text } = props

	return (
		<section id="about-section">
			<div className="container">
				<div className="row about">
					<h1 className="headline line">{title}</h1>
					<p className="text">{text}</p>
					<button className="btn download">
						<i className="lni-download"></i>
						<p> Download CV</p>
					</button>
				</div>
			</div>
		</section>
	)
}

export default AboutSection
