// src/vue/components/HeroSection.vue
<template lang="pug">
  section#hero-section
    .container-fluid
      .row
        .profile
          .me(:style="{ backgroundImage: `url('${meImage}')` }")
          .details 
            h1 {{ welcome }}
            p {{ role }}
            .hr-line
            ul
              li
                i(class="lni-phone-handset") 
                p Phone: 
                  a(:href="`tel:${contacts.phone}`") {{ contacts.phone }}
              li
                i(class="lni-envelope")
                p Email: 
                  a(:href="`mailto:${contacts.email}`") {{ contacts.email }}
              li
                i(class="lni-apartment")
                p  Address: {{ contacts.address }}
              li
                i(class="lni-calendar")
                p  Date of Birth: {{ contacts.birthdate }}
</template>

<script lang="ts">
export default {
  props: {
    welcome: String,
    role: String,
    contacts: Object
  },
  data() {
    return {
      // this needed becouse background-image: url('/images/me.png') in css not going to work
      meImage: "/images/me.png"
    }
  }
}
</script>

// src/react/components/HeroSection.tsx
import React from 'react'

const HeroSection = props => {
	const { welcome, role, contacts } = props

	return (
		<section id="hero-section">
			<div className="container-fluid">
				<div className="row">
					<div className="profile">
						<div className="me" style={{ backgroundImage: 'url("/images/me.png")' }}></div>
						<div className="details">
							<h1>{welcome}</h1>
							<p>{role}</p>
							<div className="hr-line"></div>
							<ul>
								<li>
									<i className="lni-phone-handset"></i>
									<p> Phone: <a href={`tel:${contacts.phone}`}>{contacts.phone}</a></p>
								</li>
								<li>
									<i className="lni-envelope"></i>
									<p>
										Email: <a href={`mailto:${contacts.email}`}>{contacts.email}</a>
									</p>
								</li>
								<li>
									<i className="lni-apartment"></i>
									<p> Address: {contacts.address}</p>
								</li>
								<li>
									<i className="lni-calendar"></i>
									<p> Date of Birth: {contacts.birthdate}</p>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>
	)
}

export default HeroSection
