// src/vue/App.vue
<template lang="pug">
	div.main(v-scroll="onScroll")
		navigation-bar(:top="top")
		hero-section(:welcome="texts.hero.welcome" :role="texts.hero.role" :contacts="texts.hero.contacts")
		about-section(:title="texts.about.title" :text="texts.about.text")
		experience-section(:title="texts.experience.title" :text="texts.experience.text" :timeline="timeline")
		skills-section(:title="texts.skills.title" :text="texts.skills.text" :skills="skills")
		education-section(:title="texts.education.title" :text="texts.education.text" :schools="schools")
		contact-section(:title="texts.contact.title")
		v-footer
</template>

<script lang="ts">
import NavigationBar from "./components/NavigationBar.vue"
import HeroSection from "./components/HeroSection.vue"
import AboutSection from "./components/AboutSection.vue"
import ExperienceSection from "./components/ExperienceSection.vue"
import SkillsSection from "./components/SkillsSection.vue"
import EducationSection from "./components/EducationSection.vue"
import ContactSection from "./components/ContactSection.vue"
import Footer from "./components/Footer.vue"

import { getScrollTop, debounce } from "../shared/utils"
import { getTexts, getExperienceTimeline, getSkills, getSchools } from "../shared/service"

export default {
  components: {
    NavigationBar,
    HeroSection,
    AboutSection,
    ExperienceSection,
    SkillsSection,
    EducationSection,
    ContactSection,
    "v-footer": Footer
  },
  data() {
    return {
      texts: {
        hero: {
          welcome: "",
          role: "",
          contacts: {
            phone: "",
            email: "",
            address: "",
            birthdate: ""
          }
        },
        about: {
          title: "",
          text: ""
        },
        experience: {
          title: "",
          text: ""
        },
        skills: {
          title: "",
          text: ""
        },
        education: {
          title: "",
          text: ""
        },
        contact: {
          title: ""
        }
      },
      timeline: {},
      skills: {},
      schools: {},
      top: true
    } 
  },
  async created() {
    const [texts, timeline, skills, schools] = await Promise.all([
      getTexts(),
      getExperienceTimeline(),
      getSkills(),
      getSchools()
    ])

    this.texts = texts
    this.timeline = timeline
    this.skills = skills
    this.schools = schools
  },
  methods: {
    onScroll: debounce(() => {
      this.top = getScrollTop() === 0
    }, 15)
  }
}
</script>

// src/react/App.tsx
import React, { useCallback, useEffect, useState } from "react"

import NavigationBar from "./components/NavigationBar"
import HeroSection from "./components/HeroSection"
import AboutSection from "./components/AboutSection"
import ExperienceSection from "./components/ExperienceSection"
import SkillsSection from "./components/SkillsSection"
import EducationSection from "./components/EducationSection"
import ContactSection from "./components/ContactSection"
import Footer from "./components/Footer"

import { getScrollTop, debounce } from "../shared/utils"
import { getTexts, getExperienceTimeline, getSkills, getSchools } from "../shared/service"

const App = () => {
  const [texts, setTexts] = useState({
    hero: {
      welcome: "",
      role: "adsf",
      contacts: {
        phone: "",
        email: "",
        address: "",
        birthdate: ""
      }
    },
    about: {
      title: "",
      text: ""
    },
    experience: {
      title: "",
      text: "	"
    },
    skills: {
      title: "",
      text: ""
    },
    education: {
      title: "",
      text: ""
    },
    contact: {
      title: ""
    }
  })
  const [atTop, setAtTop] = useState(true)
  const [timeline, setTimeline] = useState({})
  const [schools, setSchools] = useState({})
  const [skills, setSkills] = useState({
    languages: [],
    frameworks: [],
    technologies: []
  })

  const handleScroll = useCallback(() => {
    setAtTop(getScrollTop() === 0)
    console.log('sc')
  }, [])

  const debouncedScroll = useCallback(
    debounce(() => {}, 0),
    [handleScroll]
  )

  useEffect(() => {
    window.addEventListener("scroll", debouncedScroll)

    const loadApi = async () => {
      const [texts, timeline, skills, schools] = await Promise.all([
        await getTexts() as any,
        await getExperienceTimeline(),
        await getSkills(),
        await getSchools()
      ])

      setTexts(texts)
      setTimeline(timeline)
      setSkills(skills)
      setSchools(schools)
    }

    loadApi()

    return () => window.removeEventListener("scroll", debouncedScroll)
  }, [])

  return (
    <div className="main" onScroll={() => handleScroll()}>
      <NavigationBar atTop={atTop} />
      <HeroSection welcome={texts.hero.welcome} role={texts.hero.role} contacts={texts.hero.contacts} />
      <AboutSection title={texts.about.title} text={texts.about.text} />
      <ExperienceSection
        title={texts.experience.title}
        text={texts.experience.text}
        timeline={Object.values(timeline)}
      />
      <SkillsSection title={texts.skills.title} text={texts.skills.text} skills={skills} />
      <EducationSection title={texts.education.title} text={texts.education.text} schools={Object.values(schools)} />
      <ContactSection title={texts.contact.title} />
      <Footer />
    </div>
  )
}

export default App
