// src/vue/App.vue
<template lang="pug">
	div.main(v-scroll="onScroll")
		navigation-bar(:top="top")
		hero-section(:welcome="texts.hero.welcome" :role="texts.hero.role" :contacts="texts.hero.contacts")
		about-section(:title="texts.about.title" :text="texts.about.text")
		experience-section(:title="texts.experience.title" :text="texts.experience.text" :timeline="timeline")
		skills-section(:title="texts.skills.title" :text="texts.skills.text" :skills="skills")
		education-section(:title="texts.education.title" :text="texts.education.text" :schools="schools")
		contact-section(:title="texts.contact.title")
		v-footer
</template>

<script>
	import Vue from 'vue'

	import NavigationBar from './components/NavigationBar.vue'
	import HeroSection from './components/HeroSection.vue'
	import AboutSection from './components/AboutSection.vue'
	import ExperienceSection from './components/ExperienceSection.vue'
	import SkillsSection from './components/SkillsSection.vue'
	import EducationSection from './components/EducationSection.vue'
	import ContactSection from './components/ContactSection.vue'
	import Footer from './components/Footer.vue'

	import { getScrollTop, debounce } from '../shared/utils.js'
	import { getTexts, getExperienceTimeline, getSkills, getSchools } from '../shared/service.js'

	export default {
		components: {
			NavigationBar,
			HeroSection,
			AboutSection,
			ExperienceSection,
			SkillsSection,
			EducationSection,
			ContactSection,
			'v-footer': Footer,
		},
		data() {
			return {
				texts: {
					hero: {
						welcome: '',
						role: '',
						contacts: {
							phone: '',
							email: '',
							address: '',
							birthdate: '',
						},
					},
					about: {
						title: '',
						text: '',
					},
					experience: {
						title: '',
						text: '',
					},
					skills: {
						title: '',
						text: '',
					},
					education: {
						title: '',
						text: '',
					},
					contact: {
						title: '',
					},
				},
				timeline: {},
				skills: {},
				schools: {},
				top: true,
			}
		},
		async created() {
			this.texts = await getTexts()
			this.timeline = await getExperienceTimeline()
			this.skills = await getSkills()
			this.schools = await getSchools()
		},
		methods: {
			onScroll: debounce(function onScroll(e) {
				this.top = getScrollTop() == 0
			}, 15),
		},
	}
</script>

// src/react/App.jsx
import React, { Component } from 'react'

import NavigationBar from './components/NavigationBar'
import HeroSection from './components/HeroSection'
import AboutSection from './components/AboutSection'
import ExperienceSection from './components/ExperienceSection'
import SkillsSection from './components/SkillsSection'
import EducationSection from './components/EducationSection'
import ContactSection from './components/ContactSection'
import Footer from './components/Footer'

import { getScrollTop, debounce } from '../shared/utils.js'
import { getTexts, getExperienceTimeline, getSkills } from '../shared/service.js'

class App extends Component {
	constructor(props) {
		super(props)

		this.state = {
			texts: {
				hero: {
					welcome: '',
					role: 'adsf',
					contacts: {
						phone: '',
						email: '',
						address: '',
						birthdate: ''
					}
				},
				about: {
					title: '',
					text: ''
				},
				experience: {
					title: '',
					text: '	'
				},
				skills: {
					title: '',
					text: ''
				},
				education: {
					title: '',
					text: ''
				},
				contact: {
					title: ''
				}
			},
			timeline: {},
			skills: {
				languages: [],
				frameworks: [],
				technologies: []
			},
			schools: {},
			top: true
		}

		this.debounceScroll = debounce(this.handleScroll.bind(this), 0)
	}

	componentWillUnmount() {
		window.removeEventListener('scroll', this.debounceScroll)
	}

	handleScroll(e) {
		this.setState({
			top: getScrollTop() == 0
		})
	}

	async componentWillMount() {
		window.addEventListener('scroll', this.debounceScroll)

		let data = await getTexts()
		this.setState({ texts: data })
		data = await getExperienceTimeline()
		this.setState({ timeline: data })
		data = await getSkills()
		this.setState({ skills: data })
	}

	render() {
		const { texts, top, timeline, skills, schools } = this.state

		return (
			<div className="main" onScroll={this.handleScroll}>
				<NavigationBar top={top} />
				<HeroSection welcome={texts.hero.welcome} role={texts.hero.role} contacts={texts.hero.contacts} />
				<AboutSection title={texts.about.title} text={texts.about.text} />
				<ExperienceSection title={texts.experience.title} text={texts.experience.text} timeline={Object.values(timeline)} />
				<SkillsSection title={texts.skills.title} text={texts.skills.text} skills={skills} />
				<EducationSection title={texts.education.title} text={texts.education.text} schools={Object.values(schools)} />
				<ContactSection title={texts.contact.title} />
				<Footer />
			</div>
		)
	}
}

export default App
